[tool.black]
line-length = 90
target-version = ['py36']

[tool.coverage.run]
branch = true

[tool.coverage.report]
precision = 2

[tool.isort]
include_trailing_comma = true
use_parentheses = true
known_first_party = 'pytest_deadfixtures'
known_localfolder = 'tests'
line_length = 90
multi_line_output = 3
force_grid_wrap = 0
