[tox]
envlist = py{310,311,312,313,314}-pytest{8,9}, py, pypy3, lint

[gh-actions]
python =
    3.10: py310-pytest{8,9}
    3.11: py311-pytest{8,9}
    3.12: py312-pytest{8,9}
    3.13: py313-pytest{8,9}, lint
    3.14: py314-pytest{8,9}
    pypy-3.8: pypy3
    pypy-3.9: pypy3

[testenv]
deps =
    -rrequirements.txt
    pytest8: pytest>=8.0,<9.0
    pytest9: pytest>=9.0,<10.0
commands = pytest --cov pytest_deadfixtures -v --cov-report term-missing --cov-report xml

[testenv:lint]
skip_install = true
deps = pre-commit
commands =
    pre-commit install
    pre-commit run -v -a

[flake8]
ignore = E501,W503
